version: '3'
services:
  db:
    image: postgres:latest
    ports:
      - "5433:5433"
  server:
    build:
      context: ./src/tournament_server
      dockerfile: Dockerfile-alternative
    image: tournament_server
    command: "go run server.go"
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - tournament.env